"""Initial revision

Revision ID: 25bc5992cb40
Revises: f193c82750b3
Create Date: 2024-10-20 17:24:04.345019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25bc5992cb40'
down_revision: Union[str, None] = 'f193c82750b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'fname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'lname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table(
        'comics',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('description', sa.Text, server_default="Описание комикса", nullable=False),
        sa.Column('rating', sa.Integer, nullable=True),
        sa.Column('user_id', sa.Integer, sa.ForeignKey('users.id', ondelete="CASCADE"), nullable=False),
        sa.Column('created_at', sa.DateTime, server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime, server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False)
    )
    op.create_table(
        'comments',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('description', sa.String(length=255), nullable=False),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('comic_id', sa.Integer(), sa.ForeignKey('comics.id'), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), onupdate=sa.func.now()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'lname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'fname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('comics')
    op.drop_table('comments')

    # ### end Alembic commands ###
