"""Initial revision

Revision ID: f193c82750b3
Revises: 1d4925a72e00
Create Date: 2024-10-16 00:52:26.165693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f193c82750b3'
down_revision: Union[str, None] = '1d4925a72e00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Убедитесь, что добавление колонки закомментировано или удалено.
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем колонку 'profile_picture', если она существует.
    # Поскольку в Alembic нет встроенной функции has_column, используем SQL для проверки.
    conn = op.get_bind()
    
    if conn.has_table('users'):
        result = conn.execute("SELECT column_name FROM information_schema.columns WHERE table_name='users'")
        columns = [row[0] for row in result]
        if 'profile_picture' in columns:
            op.drop_column('users', 'profile_picture')
    # ### end Alembic commands ###
